# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: cardoe/yocto:pyro

steps:
- checkout: self

- script: |
    cd $(Pipeline.Workspace)
    pwd
    git clone --depth 1 -b master --single-branch git://git.yoctoproject.org/poky.git
    git clone --depth 1 -b master --single-branch git://git.openembedded.org/meta-openembedded.git poky/meta-openembedded
    ln -s $(Build.Repository.LocalPath) poky/meta-rust
  displayName: 'Fetch layers'

- script: |
    pwd
    ls $(Pipeline.Workspace)
    ls $(Pipeline.Workspace)/poky
  displayName: 'ls'
